spring:
  profiles:
    active: development
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myClevertecDB
    username: alex
    password: alex
    hikari:
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:changelog.yaml
  cache:
    algorithm: LRU
    max-size: 1000

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql://hostname/databasename
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: production
  database:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myClevertecDB
    username: alex
    password: alex

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect